title: Tari Shakira PIF
description: >
  My name is Tari Shakira
  <br><br>
  I'm Math Student at Pakuan University
  <br><br>
  I live in Indonesia
  <br><br>
  Now I'm learning Data Science at Zenius Education
  <br><br>
  <a href="https://www.linkedin.com/in/tari-shakira-229840211/">View My LinkedIn Profile</a>
  <br><br>
  <a href="https://www.instagram.com/tshakiraa/">View My Instagram Profile</a>
  
theme: jekyll-theme-minimal
